name: Run main.py

on:
  workflow_dispatch:

jobs:
  run_main:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Run main.py
      run: python main.py
